// TCS NQT — Verbal Ability Questions (Source: PrepInsta, GeeksforGeeks, TCS Papers)
const VERBAL_QUESTIONS = [
  {id:"V1",topic:"Error Spotting",prob:"certain",diff:"easy",
    q:"Find the error: 'Each of the students have completed their assignment on time.'",
    options:["have → has","their → his","on → in","No error"],answer:0,
    explanation:"'Each' is singular, so verb must be 'has'. Correct: 'Each of the students has completed...'"},
  {id:"V2",topic:"Error Spotting",prob:"certain",diff:"easy",
    q:"Find the error: 'Neither the manager nor the employees was present at the meeting.'",
    options:["was → were","nor → or","at → in","No error"],answer:0,
    explanation:"When 'neither...nor' connects singular and plural, verb agrees with the nearer subject (employees = plural). Use 'were'."},
  {id:"V3",topic:"Error Spotting",prob:"very-high",diff:"medium",
    q:"Find the error: 'He is one of those persons who believes in hard work.'",
    options:["believes → believe","those → these","in → on","No error"],answer:0,
    explanation:"'Who' refers to 'persons' (plural), so verb should be 'believe'."},
  {id:"V4",topic:"Synonyms",prob:"certain",diff:"easy",
    q:"Choose the synonym of 'Benevolent':",
    options:["Kind","Cruel","Greedy","Strict"],answer:0,
    explanation:"Benevolent means well-meaning, kindly, generous. Synonym: Kind."},
  {id:"V5",topic:"Synonyms",prob:"certain",diff:"easy",
    q:"Choose the synonym of 'Pragmatic':",
    options:["Practical","Theoretical","Idealistic","Dreamy"],answer:0,
    explanation:"Pragmatic means dealing with things sensibly and realistically. Synonym: Practical."},
  {id:"V6",topic:"Synonyms",prob:"very-high",diff:"medium",
    q:"Choose the synonym of 'Ubiquitous':",
    options:["Omnipresent","Rare","Unique","Scarce"],answer:0,
    explanation:"Ubiquitous means present, found everywhere. Synonym: Omnipresent."},
  {id:"V7",topic:"Antonyms",prob:"certain",diff:"easy",
    q:"Choose the antonym of 'Ephemeral':",
    options:["Permanent","Brief","Temporary","Momentary"],answer:0,
    explanation:"Ephemeral means lasting for a very short time. Antonym: Permanent."},
  {id:"V8",topic:"Antonyms",prob:"certain",diff:"easy",
    q:"Choose the antonym of 'Verbose':",
    options:["Concise","Lengthy","Talkative","Wordy"],answer:0,
    explanation:"Verbose means using more words than needed. Antonym: Concise."},
  {id:"V9",topic:"Antonyms",prob:"very-high",diff:"medium",
    q:"Choose the antonym of 'Gregarious':",
    options:["Solitary","Social","Friendly","Outgoing"],answer:0,
    explanation:"Gregarious means fond of company. Antonym: Solitary."},
  {id:"V10",topic:"Sentence Completion",prob:"certain",diff:"easy",
    q:"The scientist's research was so _____ that it changed the entire field overnight.",
    options:["groundbreaking","mundane","trivial","ordinary"],answer:0,
    explanation:"Context implies a dramatic positive impact. 'Groundbreaking' fits best."},
  {id:"V11",topic:"Sentence Completion",prob:"certain",diff:"easy",
    q:"The manager _____ the new policy at yesterday's meeting.",
    options:["announced","announcing","announce","announces"],answer:0,
    explanation:"Past tense needed ('yesterday'). 'Announced' is correct."},
  {id:"V12",topic:"Sentence Completion",prob:"very-high",diff:"medium",
    q:"Despite his _____, the athlete continued to train with unwavering dedication.",
    options:["injury","success","health","victory"],answer:0,
    explanation:"'Despite' implies contrast. An injury is something to overcome. Answer: injury."},
  {id:"V13",topic:"Reading Comprehension",prob:"certain",diff:"medium",
    q:"Passage: 'Artificial intelligence is transforming industries at an unprecedented pace. From healthcare to finance, AI algorithms are now capable of tasks previously thought to require human intelligence.' — What is the main idea?",
    options:["AI is rapidly changing many industries","AI will replace all humans","Finance uses the most AI","Healthcare doesn't use AI"],answer:0,
    explanation:"The passage discusses AI transforming industries at an unprecedented pace."},
  {id:"V14",topic:"Reading Comprehension",prob:"certain",diff:"medium",
    q:"Passage: 'Climate change poses significant threats to biodiversity. Rising temperatures are causing species migration patterns to shift, leading to ecosystem imbalances.' — What threatens biodiversity?",
    options:["Climate change","Deforestation","Pollution","Overpopulation"],answer:0,
    explanation:"The passage explicitly states climate change poses threats to biodiversity."},
  {id:"V15",topic:"Para Jumbles",prob:"certain",diff:"medium",
    q:"Arrange: P) He went to the market. Q) He bought vegetables. R) He cooked dinner. S) He came home.",
    options:["P-Q-S-R","P-S-Q-R","S-P-Q-R","Q-P-S-R"],answer:0,
    explanation:"Logical order: Went to market → Bought vegetables → Came home → Cooked dinner. P-Q-S-R."},
  {id:"V16",topic:"Para Jumbles",prob:"very-high",diff:"medium",
    q:"Arrange: P) The seeds germinated in a week. Q) She watered them daily. R) She planted seeds in the garden. S) Beautiful flowers bloomed.",
    options:["R-Q-P-S","P-Q-R-S","R-P-Q-S","Q-R-P-S"],answer:0,
    explanation:"Logical: Plant → Water → Germinate → Bloom. R-Q-P-S."},
  {id:"V17",topic:"Error Spotting",prob:"very-high",diff:"medium",
    q:"Find the error: 'The furniture in both the rooms are identical.'",
    options:["are → is","both → all","in → at","No error"],answer:0,
    explanation:"'Furniture' is uncountable noun, takes singular verb 'is'."},
  {id:"V18",topic:"Sentence Completion",prob:"high",diff:"easy",
    q:"The professor spoke so _____ that even complex topics were easy to understand.",
    options:["lucidly","vaguely","confusingly","rapidly"],answer:0,
    explanation:"Context: complex topics became easy = clear explanation. Lucidly means clearly."},
  {id:"V19",topic:"Synonyms",prob:"high",diff:"easy",
    q:"Choose the synonym of 'Meticulous':",
    options:["Careful","Careless","Rough","Quick"],answer:0,
    explanation:"Meticulous means showing great attention to detail. Synonym: Careful."},
  {id:"V20",topic:"Antonyms",prob:"high",diff:"easy",
    q:"Choose the antonym of 'Frugal':",
    options:["Extravagant","Thrifty","Economical","Prudent"],answer:0,
    explanation:"Frugal means sparing with money. Antonym: Extravagant."},
  {id:"V21",topic:"Sentence Completion",prob:"high",diff:"medium",
    q:"The company decided to _____ its operations to reduce costs.",
    options:["streamline","expand","diversify","increase"],answer:0,
    explanation:"To reduce costs, companies streamline (make more efficient) operations."},
  {id:"V22",topic:"Error Spotting",prob:"high",diff:"easy",
    q:"Find the error: 'One of my friend is a doctor.'",
    options:["friend → friends","is → are","a → the","No error"],answer:0,
    explanation:"'One of' must be followed by a plural noun. Correct: 'One of my friends'."},
  {id:"V23",topic:"Reading Comprehension",prob:"very-high",diff:"hard",
    q:"Passage: 'Remote work has become a permanent fixture in the corporate landscape. Studies show 70% of companies now offer flexible work arrangements.' — What can be inferred?",
    options:["Most companies support remote work","All employees work from home","Remote work is temporary","Companies oppose flexible work"],answer:0,
    explanation:"70% offering flexible arrangements means most companies support it."},
  {id:"V24",topic:"Synonyms",prob:"high",diff:"medium",
    q:"Choose the synonym of 'Tenacious':",
    options:["Persistent","Weak","Timid","Fragile"],answer:0,
    explanation:"Tenacious means holding firmly, persistent. Synonym: Persistent."},
  {id:"V25",topic:"Para Jumbles",prob:"high",diff:"hard",
    q:"Arrange: P) This led to a breakthrough in medicine. Q) Scientists studied the DNA structure. R) They identified the gene responsible for the disease. S) New treatments were developed.",
    options:["Q-R-P-S","Q-P-R-S","R-Q-S-P","P-Q-R-S"],answer:0,
    explanation:"Logical: Study DNA → Identify gene → Breakthrough → New treatments. Q-R-P-S."},
  {id:"V26",topic:"Word Completion",prob:"very-high",diff:"easy",
    q:"Complete: CON_E_UENCE",
    options:["S,Q (CONSEQUENCE)","S,S","Q,Q","C,S"],answer:0,
    explanation:"CONSEQUENCE — CON_S_EQUENCE."},
  {id:"V27",topic:"Word Completion",prob:"high",diff:"easy",
    q:"Complete: A_QUI_ITION",
    options:["C,S (ACQUISITION)","C,T","S,S","Q,S"],answer:0,
    explanation:"ACQUISITION — A_C_QUI_S_ITION."},
  {id:"V28",topic:"Error Spotting",prob:"high",diff:"medium",
    q:"Find the error: 'She prefers coffee than tea.'",
    options:["than → to","coffee → coffees","She → Her","No error"],answer:0,
    explanation:"'Prefer' is followed by 'to', not 'than'. Correct: 'prefers coffee to tea'."},
  {id:"V29",topic:"Sentence Completion",prob:"high",diff:"medium",
    q:"His _____ approach to the problem impressed the entire board of directors.",
    options:["innovative","conventional","traditional","outdated"],answer:0,
    explanation:"Impressive approach implies something new. 'Innovative' fits best."},
  {id:"V30",topic:"Antonyms",prob:"high",diff:"medium",
    q:"Choose the antonym of 'Candid':",
    options:["Secretive","Honest","Open","Frank"],answer:0,
    explanation:"Candid means truthful, straightforward. Antonym: Secretive."},
  {id:"V31",topic:"Synonyms",prob:"high",diff:"medium",
    q:"Choose the correct synonym for EXACERBATE.",
    options:["Alleviate","Worsen","Soothe","Pacify"],answer:1,
    explanation:"Exacerbate means to make a problem, bad situation, or negative feeling worse."},
  {id:"V32",topic:"Antonyms",prob:"high",diff:"hard",
    q:"Choose the correct antonym for EPHEMERAL.",
    options:["Transient","Perennial","Fleeting","Short-lived"],answer:1,
    explanation:"Ephemeral means lasting for a very short time. Perennial means lasting for a long or infinite time."},
  {id:"V33",topic:"Error Spotting",prob:"certain",diff:"medium",
    q:"Find the error: 'None of the two brothers are going to attend the party tonight.'",
    options:["None of the","two brothers are","going to attend","No error"],answer:0,
    explanation:"'None' is used for more than two things/persons. For exactly two, use 'Neither'. So it should be 'Neither of the two brothers is...'"},
  {id:"V34",topic:"Sentence Completion",prob:"very-high",diff:"medium",
    q:"The principal was _______ by the student's lack of respect.",
    options:["Appalled","Appeased","Exhilarated","Oblivious"],answer:0,
    explanation:"Appalled means horrified or shocked, which fits the context of bad behavior. Appeased means pacified, Exhilarated means thrilled."},
  {id:"V35",topic:"Para Jumbles",prob:"high",diff:"hard",
    q:"Order the sentences: A: It was a cold winter night. B: We decided to light a fire. C: However, the wood was wet. D: So we had to sleep in our coats.",
    options:["ABCD","ABDC","CABD","BDAC"],answer:0,
    explanation:"A completely logical flow: A establishes context, B shows intention, C presents an obstacle, D shows the consequence. ABCD."},
  {id:"V36",topic:"Reading Comprehension",prob:"certain",diff:"medium",
    q:"Read: The Amazon rainforest is the world's largest tropical rainforest. It covers over 5.5 million square kilometers and is vital for controlling global warming. Which of the following is true?",
    options:["It regulates local climate only","It spans exactly 5 million km²","It plays a key role in slowing global warming","It is the second-largest rainforest"],answer:2,
    explanation:"The passage explicitly states it is 'vital for controlling global warming'."},
  {id:"V37",topic:"Sentence Correction",prob:"very-high",diff:"medium",
    q:"Correct the sentence: 'She is one of the best mother in the world.'",
    options:["She is one of the best mothers in the world","She is one of a best mother in the world","She is one of the best mother of the world","No correction needed"],answer:0,
    explanation:"The phrase 'one of the' is always followed by a plural noun (mothers)."},
  {id:"V38",topic:"Word Completion",prob:"high",diff:"hard",
    q:"Choose the word that means 'fluent or persuasive in speaking or writing'.",
    options:["Eloquent","Reticent","Taciturn","Garrulous"],answer:0,
    explanation:"Eloquent means persuasive and articulate. Reticent and taciturn mean reserved/quiet. Garrulous means talkative (usually negatively)."},
  {id:"V39",topic:"Error Spotting",prob:"very-high",diff:"medium",
    q:"Identify the error: 'I prefer coffee than tea in the morning.'",
    options:["I prefer","coffee than","tea in the","morning"],answer:1,
    explanation:"The verb 'prefer' takes the preposition 'to', not 'than'. It should be 'coffee to tea'."},
  {id:"V40",topic:"Sentence Completion",prob:"high",diff:"easy",
    q:"You must ____________ your career if you really want to succeed.",
    options:["focus on","divert from","procrastinate","abandon"],answer:0,
    explanation:"'Focus on' is the logically sound completion for striving to succeed."},
  {id:"V41",topic:"Synonyms",prob:"very-high",diff:"medium",
    q:"What is the synonym of 'CANDID'?",
    options:["Deceptive","Frank","Guarded","Tactful"],answer:1,
    explanation:"Candid means truthful and straightforward, i.e., Frank."},
  {id:"V42",topic:"Error Spotting",prob:"certain",diff:"hard",
    q:"Identify the error: 'He has been working here since five years.'",
    options:["He has been","working here","since five","years"],answer:2,
    explanation:"'Since' is used for a specific point in time (since 2019). For a duration, 'for' is used ('for five years')."},
  {id:"V43",topic:"Word Completion",prob:"high",diff:"medium",
    q:"A person who is incapable of making mistakes is absolutely ________.",
    options:["Infallible","Gullible","Invincible","Ineffable"],answer:0,
    explanation:"Infallible means incapable of making mistakes or being wrong."},
  {id:"V44",topic:"Antonyms",prob:"very-high",diff:"easy",
    q:"Select the antonym for 'BENEVOLENT'.",
    options:["Generous","Malevolent","Charitable","Kind"],answer:1,
    explanation:"Benevolent means well-meaning and kindly. Malevolent means wishing evil to others."},
  {id:"V45",topic:"Para Jumbles",prob:"high",diff:"medium",
    q:"Order: P: Eventually, it became a massive tree. Q: I planted a tiny seed in my garden. R: The birds built nests in its branches. S: For months, I watered it daily.",
    options:["QSPR","QPSR","SQPR","RQSP"],answer:0,
    explanation:"Chronological order: Planted seed (Q), watered it (S), became a tree (P), birds built nests (R). QSPR."}
];
